all: brvk.cpp ../graph/graph.cpp ../set/set.cpp
	clang++ -std=c++11 brvk.cpp ../graph/graph.cpp ../set/set.cpp -o boruv

g: brvk.cpp ../graph/graph.cpp ../set/set.cpp
	g++ -std=c++11 -g brvk.cpp ../graph/graph.cpp ../set/set.cpp -o boruv
